# Generated by Django 3.2.3 on 2021-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('Deactivated', 'Deactivated')], default='Active', max_length=11),
        ),
    ]
