# Generated by Django 3.2.3 on 2021-06-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_available_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_bal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
