# Generated by Django 3.2.3 on 2021-07-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
